<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< HEAD
=======
<<<<<<< HEAD
<testsuite hostname="LitoSoler" name="Default test" tests="3" failures="1" timestamp="18 Jan 2021 19:31:42 GMT" time="196.806" errors="0">
  <testcase name="login" time="7.513" classname="com.timp.test.BRB.ValidacaoEstruturas.ATRCamposAdicionaisOrdemVendas"/>
  <testcase name="brbEntrar" time="28.056" classname="com.timp.test.BRB.ValidacaoEstruturas.ATRCamposAdicionaisOrdemVendas"/>
  <testcase name="verificar" time="148.411" classname="com.timp.test.BRB.ValidacaoEstruturas.ATRCamposAdicionaisOrdemVendas">
    <failure type="java.lang.AssertionError" message="Os dados não concordam com os establecidos expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Os dados não concordam com os establecidos expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.timp.test.BRB.ValidacaoEstruturas.ATRCamposAdicionaisOrdemVendas.verificar(ATRCamposAdicionaisOrdemVendas.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verificar -->
=======
>>>>>>> branch 'master' of https://github.com/salc1997/TIMP_R1.git
<testsuite hostname="DESKTOP-BNBDMGT" failures="0" tests="3" name="Default test" time="363.168" errors="0" timestamp="18 Jan 2021 23:28:53 GMT">
  <testcase classname="com.timp.test.TDK.Kpis.Edicao.KpisEdicaoGrafico" name="login" time="8.322"/>
  <testcase classname="com.timp.test.TDK.Kpis.Edicao.KpisEdicaoGrafico" name="acessarTDK" time="24.896"/>
  <testcase classname="com.timp.test.TDK.Kpis.Edicao.KpisEdicaoGrafico" name="Grafico" time="315.79"/>
>>>>>>> branch 'master' of https://github.com/salc1997/TIMP_R1.git
</testsuite> <!-- Default test -->
