<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LitoSoler" name="com.timp.test.DFG.SPED.ESocial.S1210.S1210GerarDadosDoEventoCriar" tests="11" failures="0" timestamp="19 Dec 2020 01:09:03 GMT" time="438.142" errors="1">
  <testcase name="verificarInsert" time="52.463" classname="com.timp.test.DFG.SPED.ESocial.S1210.S1210GerarDadosDoEventoCriar">
    <error type="java.lang.AssertionError" message="O registro não foi criado com sucesso expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: O registro não foi criado com sucesso expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.timp.test.DFG.SPED.ESocial.S1210.S1210GerarDadosDoEventoCriar.verificarInsert(S1210GerarDadosDoEventoCriar.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verificarInsert -->
  <testcase name="arquivosVerificar" time="39.119" classname="com.timp.test.DFG.SPED.ESocial.S1210.S1210GerarDadosDoEventoCriar"/>
  <testcase name="mdrEntrar" time="40.475" classname="com.timp.test.DFG.SPED.ESocial.S1210.S1210GerarDadosDoEventoCriar"/>
  <testcase name="informacaoS1200" time="17.236" classname="com.timp.test.DFG.SPED.ESocial.S1210.S1210GerarDadosDoEventoCriar"/>
  <testcase name="editarS1200" time="43.166" classname="com.timp.test.DFG.SPED.ESocial.S1210.S1210GerarDadosDoEventoCriar"/>
  <testcase name="criarS1200" time="94.226" classname="com.timp.test.DFG.SPED.ESocial.S1210.S1210GerarDadosDoEventoCriar"/>
  <testcase name="executarS1200" time="87.687" classname="com.timp.test.DFG.SPED.ESocial.S1210.S1210GerarDadosDoEventoCriar"/>
  <testcase name="enviarInsert" time="18.697" classname="com.timp.test.DFG.SPED.ESocial.S1210.S1210GerarDadosDoEventoCriar"/>
  <testcase name="visualizarAtualizacoesBlocoApuracao" time="14.008" classname="com.timp.test.DFG.SPED.ESocial.S1210.S1210GerarDadosDoEventoCriar"/>
  <testcase name="ingresar" time="11.354" classname="com.timp.test.DFG.SPED.ESocial.S1210.S1210GerarDadosDoEventoCriar"/>
  <testcase name="visualizarS1200" time="19.711" classname="com.timp.test.DFG.SPED.ESocial.S1210.S1210GerarDadosDoEventoCriar"/>
</testsuite> <!-- com.timp.test.DFG.SPED.ESocial.S1210.S1210GerarDadosDoEventoCriar -->
